baseurl = "https://nisjs.com/"
languageCode = "rs"
title = "Niš JS"
googleAnalytics = "UA-92994407-1"
disqusShortname = "nisjs"
theme = "aglaus"
license = "MIT"

Copyright = "[NišJS](http://nisjs.com) - All code under [MIT Licence](http://opensource.org/licenses/MIT)"

[params]
  GoogleAnalyticsUserID = "UA-92994407-1"
  enableRSS = true
  Description = "JavaScript Meetups in Niš, Serbia. Our goal is to connect Niš's JavaScript community through monthly meetups."

[social]
  twitter  = "https://twitter.com/NisJSmeetups"
  facebook = "https://www.facebook.com/nisjs/"
  github = "https://github.com/nisjs"
  mail = "hello@nisjs.com"
